package com.topica.crm.bridge.odoo.entity.pipeline;

import com.fasterxml.jackson.databind.PropertyNamingStrategy;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import lombok.Data;

import java.util.LinkedList;
import java.util.List;

@Data
@JsonNaming(PropertyNamingStrategy.SnakeCaseStrategy.class)
public class OdooPipeline {
  private Integer plannedRevenue;
  private String writeDate;
  private List<Object> messagePartnerIds = new LinkedList<>();
  private String partnerName;
  private String messageMainAttachmentId;
  private String kanbanState;
  private List<Object> teamId = new LinkedList<>();
  private String activityDateDeadline;
  private String type;
  private List<Object> messageChannelIds = new LinkedList<>();
  private String activityState;
  private String partnerAddressEmail;
  private Integer meetingCount;
  private Integer messageHasErrorCounter;
  private List<Object> activityIds = new LinkedList<>();
  private String dateOpen;
  private String dateClosed;
  private Float dayOpen;
  private String function;
  private String userLogin;
  private Integer id;
  private Integer messageBounce;
  private List<Object> stateId;
  private String dateConversion;
  private List<Object> mediumId = new LinkedList<>();
  private String createDate;
  private List<Object> campaignId = new LinkedList<>();
  private String zip;
  private String partnerIsBlacklisted;
  private List<Object> tagIds = new LinkedList<>();
  private String userEmail;
  private Integer messageAttachmentCount;
  private String lastUpdate;
  private List<Object> stageId = new LinkedList<>();
  private Float probability;
  private String partnerAddressName;
  private String active;
  private String isBlacklisted;
  private List<Object> activityUserId = new LinkedList<>();
  private List<Integer> messageFollowerIds = new LinkedList<>();
  private String priority;
  private List<Object> createUid = new LinkedList<>();
  private String displayName;
  private Float dayClose;
  private List<Object> userId = new LinkedList<>();
  private String phone;
  private String name;
  private List<Object> websiteMessageIds = new LinkedList<>();
  private String emailCc;
  private List<Object> countryId = new LinkedList<>();
  private List<Object> writeUid = new LinkedList<>();
  private String messageIsFollower;
  private Integer color;
  private Float daysToConvert;
  private String city;
  private String partnerAddressPhone;
  private String description;
  private String dateDeadline;
  private String title;
  private Float saleAmountTotal;
  private Integer saleNumber;
  private String messageUnread;
  private List<Object> partnerId;
  private Float expectedRevenue;
  private String street;
  private List<Object> companyCurrency = new LinkedList<>();
  private String street2;
  private String website;
  private String contactName;
  private List<Object> companyId = new LinkedList<>();
  private String mobile;
  private List<Object> orderIds = new LinkedList<>();
  private String dateLastStageUpdate;
  private String lostReason;
  private Integer messageUnreadCounter;
  private Float daysExceedingClosing;
  private List<Object> activityTypeId = new LinkedList<>();
  private String messageHasError;
  private String dateActionLast;
  private String wonStatus;
  private String messageNeedaction;
  private String activitySummary;
  private Integer messageNeedactionCounter;
  private List<Integer> messageIds = new LinkedList<>();
  private List<Object> sourceId = new LinkedList<>();
  private String emailFrom;
  private String referred;
}
