application:
  default:
    force-use-config: false
    last-modified-at: 1552564409646
  enable:
    load-all-data: false
    load-ticket: false
  queue:
    contact: queue_contact
    deal: queue_deal
    ticket: queue_ticket
  schedule:
    cron:
      contact: 0 5 5 * * *
      deal: 0 5 5 * * *
      ticket: 0 5 5 * * *

elastic:
  search:
    host: localhost
    index:
      contact: index_contact
      deal: index_deal
      ticket: index_ticket

hubspot:
  ApiKey: ab1da19b-a24b-460a-bd1e-d3713aac7821
  ApiBase: http://api.hubapi.com


# RABBITMQ -----------------------------------------------------------------------------------------
#spring.rabbitmq:
#  ##IP
#  host: ${RABBITMQ_HOST}
#  username: ${RABBITMQ_USERNAME}
#  password: ${RABBITMQ_PASSWORD}

logging:
  level:
    com.topica.crm.bridge: DEBUG